dataset_path: dataset/emotions.csv
embedding_path: glove embedding\glove.6B.100d.txt
max_length: 100
max_features: 5000
test_size: 1000
random_state: 42
loss: sparse_categorical_crossentropy
optimizer: adam
metrics: accuracy
activation: softmax
epochs: 10
batch_size: 128
verbose: 1
validation_split: 0.2
tokenizer_path: tokenizer/tokenizer.pkl
model_path: models/model.h5